build:
  jobs:
    post_build:
      - make doc-mypy
      - make doc-coverage
    post_checkout:
      - git fetch --unshallow || true
    post_install:
      - python -m pip install --upgrade --no-cache-dir pdm
      - make dev-doc
    pre_build:
      - make changelog
  os: ubuntu-22.04
  tools:
    python: '3'
sphinx:
  fail_on_warning: true
version: 2
