stages:
  - lint_test
  - build_release
default:
  image: python:3.11
lint_title:
  interruptible: true
  only:
    - merge_requests
  script:
    - |
      if ! echo "$CI_MERGE_REQUEST_TITLE" | grep -Pq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.*"; then
        echo "The title does not conform to the Conventional Commit."
        echo "Please refer to 'https://www.conventionalcommits.org/'"
        exit 1
      fi
  stage: lint_test
ci:
  image: python:$PYTHON_VERSION
  interruptible: true
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
    - main
    - merge_requests
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  script:
    - env | sort
    - make dev
    - make lint
    - make test
    - make docs
    - make build
  stage: lint_test
package:
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  script:
    - env | sort
    - make dev-package
    - make build
    - make upload
  stage: build_release
  variables:
    TWINE_NON_INTERACTIVE: 'true'
pages:
  artifacts:
    paths:
      - public
  except:
    refs:
      - schedules
  only:
    changes:
      - docs/**/*
    refs:
      - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  script:
    - env | sort
    - make dev-docs
    - make docs-all
  stage: build_release
release:
  release:
    description: $CI_COMMIT_TAG_MESSAGE
    name: $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  script:
    - env | sort
  stage: build_release
