stages:
  - ci
  - pages-build
  - release-create
  - deploy
default:
  image: python:3.11
ci:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  image: python:$PYTHON_VERSION
  interruptible: true
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
    - main
    - merge_requests
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  script:
    - env | sort
    - make dev
    - make lint test docs build
  stage: ci
lint_title:
  interruptible: true
  only:
    - merge_requests
  script:
    - |
      if ! echo "$CI_MERGE_REQUEST_TITLE" | grep -Pq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.*"; then
        echo "The title does not conform to the Conventional Commit."
        echo "Please refer to 'https://www.conventionalcommits.org/'"
        exit 1
      fi
  stage: ci
package:
  only:
    - merge_requests
  script:
    - env | sort
    - ls -al
    - make dev-package
    - make build
    - make upload
  stage: deploy
  variables:
    TWINE_NON_INTERACTIVE: 'true'
pages:
  artifacts:
    paths:
      - public
  except:
    refs:
      - schedules
  only:
    - merge_requests
  script:
    - env | sort
    - ls -al
  stage: deploy
pages-build:
  artifacts:
    paths:
      - public
  except:
    refs:
      - schedules
  only:
    - merge_requests
  script:
    - env | sort
    - make dev-docs
    - make docs
  stage: pages-build
release-create:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - merge_requests
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  release:
    description: $CI_COMMIT_TAG_MESSAGE
    name: $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
  script:
    - env | sort
    - ls -al
  stage: release-create
