stages:
  - lint_test
  - build_release
lint:
  image: python:$PYTHON_VERSION
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
    - main
    - merge_requests
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  script:
    - env | sort
    - make dev-lint
    - make lint
  stage: lint_test
tests:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  image: python:$PYTHON_VERSION
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
    - main
    - merge_requests
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  script:
    - env | sort
    - make dev-tests
    - make tests
  stage: lint_test
package:
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  script:
    - env | sort
    - make dev-package
    - make build
    - make upload
  stage: build_release
pages:
  artifacts:
    paths:
      - public
  except:
    refs:
      - schedules
  only:
    changes:
      - docs/**/*
    refs:
      - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
      - main
  script:
    - env | sort
    - make dev-docs
    - make docs
  stage: build_release
default:
  image: python:3.11
  interruptible: true
