repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
        args:
          - '--assume-in-merge'
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
        stages:
          - push
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: requirements-txt-fixer
        args:
          - constraints/3.8.txt
          - constraints/3.9.txt
          - constraints/3.10.txt
          - constraints/3.11.txt
          - constraints/3.12.txt
          - requirements.txt
          - requirements/docs.txt
          - requirements/lint.txt
          - requirements/package.txt
          - requirements/test.txt
      - id: sort-simple-yaml
        files: .pre-commit-config.yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: pipenv run python -m mypy
        language: system
        exclude: ^template/.*
        types_or:
          - python
          - pyi
        require_serial: true
      - id: ruff
        name: ruff
        entry: pipenv run python -m ruff check --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pipenv run python -m ruff format --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: toml-sort
        name: toml-sort
        entry: pipenv run toml-sort
        language: system
        types:
          - toml
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$
