default_install_hook_types:
  - post-checkout
  - post-merge
  - pre-push
default_stages:
  - manual
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
        args:
          - '--assume-in-merge'
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
        stages:
          - pre-push
      - id: sort-simple-yaml
        files: .pre-commit-config.yaml
      - id: trailing-whitespace
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.385.0
    hooks:
      - id: renovate-config-validator
  - repo: local
    hooks:
      - id: pdm-sync
        name: pdm-sync
        entry: pdm sync
        language: python
        stages:
          - post-checkout
          - post-merge
        always_run: true
        pass_filenames: false
      - id: pdm-lock-check
        name: pdm-lock-check
        entry: pdm lock --check
        language: python
        files: ^pyproject.toml$
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: pdm run python -m mypy
        language: system
        exclude: ^template/.*
        types_or:
          - python
          - pyi
        require_serial: true
      - id: ruff
        name: ruff
        entry: pdm run python -m ruff check --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pdm run python -m ruff format --force-exclude
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: toml-sort
        name: toml-sort
        entry: pdm run toml-sort
        language: system
        types:
          - toml
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$
