build:
  jobs:
    post_build:
      - make reports
  os: ubuntu-22.04
  tools:
    python: '3'
formats:
  - pdf
  - epub
python:
  install:
    - extra_requirements:
        - docs
      method: pip
      path: .
version: 2
