build:
  jobs:
    post_build:
      - make reports
    post_install:
      - make dev-docs
  os: ubuntu-22.04
  tools:
    python: '3'
formats:
  - pdf
  - epub
sphinx:
  fail_on_warning: true
version: 2
