build:
  os: ubuntu-22.04
  tools:
    python: '3'
  jobs:
    post_build:
      - make reports
python:
  install:
    - extra_requirements:
        - docs
        - lint
        - tests
      method: pip
      path: .
version: 2
