build:
  jobs:
    post_build:
      - make docs-mypy
      - make docs-coverage
    post_checkout:
      - git fetch --unshallow || true
    post_install:
      - make dev-docs
    pre_build:
      - make changelog
  os: ubuntu-22.04
  tools:
    python: '3'
sphinx:
  fail_on_warning: true
version: 2
