build:
  jobs:
    post_build:
      - make doc-mypy
      - make doc-coverage
    post_checkout:
      - env | sort
      - git fetch --unshallow || true
      - git fetch origin xuan.hu/cancel-rtd-build-conditionally
      # Cancel building pull requests when there aren't changed in the related files and folders.
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      # Ref: https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet xuan.hu/cancel-rtd-build-conditionally -- .github/workflows/readthedocs-preview.yml .readthedocs.yaml README.md docs/ pdm.lock;
        then
          exit 183;
        fi
      # Use `git log` to check if the latest commit contains "skip ci",
      # in that case exit the command with 183 to cancel the build
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
    post_install:
      - python -m pip install --upgrade --no-cache-dir pdm
      - PDM_NO_EDITABLE=true make dev-doc
    pre_build:
      - CI_PAGES_URL=https://${READTHEDOCS_PROJECT}.readthedocs.io/${READTHEDOCS_LANGUAGE}/stable make changelog
  os: ubuntu-22.04
  tools:
    python: '3'
sphinx:
  fail_on_warning: true
version: 2
