[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "setuptools-scm",
]

[project]
authors = [
  {email = "i@huxuan.org", name = "huxuan"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
description = "A development-focused Python project template with various integrations, configurations and modules."
dynamic = [
  "dependencies",
  "optional-dependencies",
  "version",
]
keywords = [
  "development-focused",
  "project template",
]
name = "serious-scaffold"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
serious-scaffold-cli = "serious_scaffold.cli:app"

[project.urls]
homepage = "https://github.com/serious-scaffold/serious-scaffold-python/"
issue = "https://github.com/serious-scaffold/serious-scaffold-python/issues"

[tool.black]
force-exclude = '''
(
  template/.*
)
'''

[tool.coverage.report]
fail_under = 100

[tool.coverage.run]
source = [
  "serious_scaffold",
]

[tool.isort]
color_output = true
extend_skip = [
  "template",
]
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
enable_error_code = [
  "ignore-without-code",
]
exclude = [
  "template",
]
no_implicit_optional = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-l -s --durations=0"
log_cli = true
log_cli_level = "info"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_format = "%(asctime)s %(levelname)s %(message)s"
minversion = "6.0"

[tool.ruff]
extend-exclude = [
  "template",
]
fix = true
ignore = [
  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  "D203",
  "D204",
  "D213",
  "D215",
  "D400",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
]
select = ["ALL"]
src = ["src"]

[tool.ruff.per-file-ignores]
"docs/conf.py" = ["INP001"]
"test/*" = ["S101"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
docs = {file = ["requirements/docs.txt"]}
lint = {file = ["requirements/lint.txt"]}
package = {file = ["requirements/package.txt"]}
test = {file = ["requirements/test.txt"]}

[tool.setuptools_scm]

[tool.tomlsort]
all = true
in_place = true
trailing_comma_inline_array = true
