name: CommitLint
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  commitlint:
    container:
      image: commitlint/commitlint:19.4.1@sha256:c5300cc69d74bea0d9d80c60f0ec0a9c59f3e6108ac28f736aeb2ffe151159d9
    runs-on: ubuntu-22.04
    steps:
      - run: env | sort
      - name: Validate the latest commit message with commitlint
        if: github.event_name == 'push'
        run: echo "${{ github.event.head_commit.message }}" | npx commitlint -x @commitlint/config-conventional
      - name: Validate pull request title with commitlint
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint -x @commitlint/config-conventional
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  push:
    branches:
      - main
