name: CI
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version: ${{ matrix.python-version }}
      - id: pages
        name: Setup pages
        uses: actions/configure-pages@v4
      - run: env | sort
      - run: make dev
      - run: make lint
      - run: make test
      - run: CI_PAGES_URL=${{ steps.pages.outputs.base_url }} make doc
      - run: make build
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
  consistency:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version: '3.12'
      - run: env | sort
      - name: Install copier for template rendering using pipx
        run: pipx install copier
      - name: Generate the project with the default value
        run: |
          find . -maxdepth 1 | grep -vE '(\.|template|includes|\.git|copier\.yaml|pdm\.lock)$' | xargs -I {} rm -r {}
          copier copy -d repo_host_type=gitlab.com -r HEAD -f . .
          rm .copier-answers.yml
          copier copy -r HEAD -f . .
          rm .copier-answers.yml
      - run: git diff
      - run: git status --porcelain
      - run: test -z "$(git status --porcelain)"
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
