name: CI
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@c050bdcb2405837648035b6678c75609d53a749f # v4
        with:
          cache: true
          python-version: ${{ matrix.python-version }}
      - id: pages
        name: Setup pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
      - run: env | sort
      - run: make dev
      - run: make lint
      - run: make test
      - run: CI_PAGES_URL=${{ steps.pages.outputs.base_url }} make doc
      - run: make build
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
  consistency:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ubuntu-22.04
    steps:
      - run: env | sort
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - run: pipx install copier
      - run: make consistency
      - run: git diff
      - run: git status --porcelain
      - run: test -z "$(git status --porcelain)"
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
