name: DevContainer
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  dev-container-publish:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Build and push dev container
        env:
          SOURCE_DATE_EPOCH: 0
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5.2.0
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/dev-cache:py${{ matrix.python-version }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/dev-cache:py${{ matrix.python-version }},mode=max
          file: .devcontainer/Dockerfile
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dev:py${{ matrix.python-version }}
          target: dev
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/Dockerfile
      - .devcontainer/Dockerfile.dockerignore
      - .github/workflows/devcontainer.yml
  workflow_dispatch: null
