jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Set up Python with multiple versions.
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: |
            3.8
            3.9
            3.10
            3.11
      - name: Install pipenv using pipx
        run: pipx install pipenv
      - name: Generate constraints for all supported Python versions
        run: |
          PYTHON_VERSION=3.8 make constraints
          PYTHON_VERSION=3.9 make constraints
          PYTHON_VERSION=3.10 make constraints
          PYTHON_VERSION=3.11 make constraints
      - name: Sync template
        run: cp -rf constraints/* template/constraints/
      - run: |
          git commit -a -m "Update constraints and sync template."
          git push
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title for Conventional Commit Format
        run: |
          if ! echo "${{ github.event.pull_request.title }}" | grep -Pq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.*"; then
            echo "The title does not conform to the Conventional Commit."
            echo "Please refer to 'https://www.conventionalcommits.org/'"
            exit 1
          fi
name: Pull Request Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
