jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title for Conventional Commit Format
        run: echo "${{ github.event.pull_request.title }}" | grep -Pq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.*" || exit 1
name: Lint pull request title
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
