name: Read the Docs Pull Request Preview
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@cc0920454cf03ca8a3fbd3cbaa2ce2e509e70636 # v1
        with:
          project-slug: ss-python
on:
  pull_request_target:
    types:
      - opened
permissions:
  pull-requests: write
