name: Read the Docs Pull Request Preview
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1.2
        with:
          project-slug: ss-python
on:
  pull_request_target:
    types:
      - opened
permissions:
  pull-requests: write
